apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: goldbar-eks-01
  region: ap-east-1
  version: "1.34"

vpc:
  id: "vpc-077f527b6dcf3c2c8"
  subnets:
    public:
      ap-east-1a:
        id: "subnet-0202ff426e184b6e0"
      ap-east-1b:
        id: "subnet-0f1dc9c0283fa2129"
    private:
      ap-east-1a:
        id: "subnet-0c79aec3ce99ee21c"
      ap-east-1b:
        id: "subnet-09720146aacb4b44d"
      ap-east-1c:
        id: "subnet-0e96a5b7e0177c929"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-node
        namespace: kube-system
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        
managedNodeGroups:
  - name: ng-workers
    instanceType: t3.small
    desiredCapacity: 3
    minSize: 1
    maxSize: 4
    privateNetworking: true
    maxPodsPerNode: 110
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        cloudWatch: true
    labels:
      nodegroup-type: workers
    tags:
      Environment: production
